In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import stripROtools
import matplotlib.pyplot as plt
import matplotlib.cm as cmx
import matplotlib
from mpl_toolkits.mplot3d import Axes3D
from scipy import stats
from scipy.optimize import curve_fit
from scipy.stats import crystalball



In [15]:
# Load exp data
df_exp = pd.read_pickle("./data/resolution_exp.pk")

# Load sim data
df_sim = pd.read_pickle("./data/resolution_sim.pk")


In [16]:
df_exp 

Name                                              x_res  \
0    UH_DLC_a  [49.37624293185143, 42.72732761172925, 49.1217...   
1  UH_NoDLC_a  [55.29362863299129, 40.92980379868777, 46.4563...   
2         UoS  [95.7666736435635, 44.32468606574737, 93.09687...   

                                           x_res_err  \
0  [8.060205852786922, 4.843954175457175, 6.14201...   
1  [6.650559508891235, 4.203016700035666, 4.82912...   
2  [39.46061294585079, 9.665033960326667, 31.0335...   

                                               y_res  \
0  [53.78063311920274, 39.710213566939714, 35.187...   
1  [33.404396882852375, 47.79383415850631, 46.433...   
2  [34.53300909012184, 44.89354369593178, 41.4252...   

                                           y_res_err  \
0  [11.02167185664383, 3.935292435289187, 3.92273...   
1  [3.7852412858994704, 10.648521574635893, 7.888...   
2  [6.996992631099758, 9.015357296172645, 12.7678...   

                       abs_z  
0  [0.2, 0.4, 0.6, 0.8, 1.0]  
1  [0.2, 0.4, 0.6, 0.8, 1.0]  
2  [0.2, 0.4, 0.6, 0.8, 1.0]

In [17]:
df_sim.iloc[0].x_res

array([36.81296509, 40.78488265, 39.62488676, 38.18504553, 38.08332042])

In [19]:
x_vals = df_sim.iloc[0].x_res
sigmas = np.sqrt(np.array(df_sim.iloc[0].x_res_err)**2 +np.array(df_exp.iloc[0].x_res_err)**2)
y_vals = df_exp.iloc[0].x_res


In [20]:
sigmas


array([8.23602268, 5.10766496, 6.38082286, 6.90182726, 6.80467478])

In [22]:
# fit function
def fit(x, a):
	return np.sqrt(x**2 + a**2)



# UH DLC quadrant a, x strips
x_vals = df_sim.iloc[0].x_res
sigmas = np.sqrt(np.array(df_sim.iloc[0].x_res_err)**2 +np.array(df_exp.iloc[0].x_res_err)**2)
y_vals = df_exp.iloc[0].x_res

coeff, covar = curve_fit(fit, x_vals, y_vals, sigma=sigmas, absolute_sigma=True)





In [23]:
coeff

array([35.44210966])

In [26]:
np.sqrt(np.diag(covar))

array([4.29387054])